Repository kayabaakihiko13/Qadiriyah, pull requests merged in 2023-08, with the labels that each got.

#1 feat: add Algorithm of Combinatorial
  libs/math/math.hh
Labels: ready-to-merge

#2 feat: improvement `qadiriyah`
  .clang-format
  .github/workflows/testing-cpp.yml
  .gitignore
  libs/math/math.hh
  libs/math/static.hh
  libs/math/trigonometric.hh
  libs/utils/constant.h
  test/main.cpp
  testing/.gitignore
  testing/CMakeLists.txt
  testing/test/math_test.cpp
  testing/testing_main.cpp
Labels: documentation, help wanted, invalid, ready-to-merge

#6 feat: Update Unit Testing Math and Statistic Algorithm
  libs/math/static.hh
  testing/CMakeLists.txt
  testing/test/math_test.cpp
  testing/test/statistic_test.cpp
Labels: documentation

#9 feat: Update Unit Testing,Function and Documentation Statistic for Al…
  libs/math/math.hh
  libs/math/static.hh
  libs/math/trigonometric.hh
  testing/test/math_test.cpp
  testing/test/statistic_test.cpp
Labels: documentation, ready-to-merge
